[package]
name = "variables"
version = "2.3.4"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm= "0.17.5"
rusty_audio= "1.1.4"
rusty_time= "0.11.0"